#!/bin/bash

CURRCODE=$1

CURRCODE="${CURRCODE^^}"

if [ "$CURRCODE" = "CAD" ]; then
	CURRSYM="$"
elif [ "$CURRCODE" = "USD" ]; then
	CURRSYM="$"
elif [ "$CURRCODE" = "AUD" ]; then
	CURRSYM="$"
elif [ "$CURRCODE" = "ALL" ]; then
	CURRSYM="Lek"
elif [ "$CURRCODE" = "AFN" ]; then
	CURRSYM="؋"
elif [ "$CURRCODE" = "ARS" ]; then
	CURRSYM="$"
elif [ "$CURRCODE" = "AWG" ]; then
	CURRSYM="ƒ"
elif [ "$CURRCODE" = "AZN" ]; then
	CURRSYM="ман"
elif [ "$CURRCODE" = "BSD" ]; then
	CURRSYM="$"
elif [ "$CURRCODE" = "BBD" ]; then
	CURRSYM="$"
elif [ "$CURRCODE" = "BYN" ]; then
	CURRSYM="Br"
elif [ "$CURRCODE" = "BZD" ]; then
	CURRSYM="BZ$"
elif [ "$CURRCODE" = "BMD" ]; then
	CURRSYM="$"
elif [ "$CURRCODE" = "BOB" ]; then
	CURRSYM="$b"
elif [ "$CURRCODE" = "BAM" ]; then
	CURRSYM="KM"
elif [ "$CURRCODE" = "BWP" ]; then
	CURRSYM="P"
elif [ "$CURRCODE" = "BGN" ]; then
	CURRSYM="лв"
elif [ "$CURRCODE" = "BRL" ]; then
	CURRSYM="R$"
elif [ "$CURRCODE" = "BND" ]; then
	CURRSYM="$"
elif [ "$CURRCODE" = "KHR" ]; then
	CURRSYM="៛"
elif [ "$CURRCODE" = "KYD" ]; then
	CURRSYM="$"
elif [ "$CURRCODE" = "CLP" ]; then
	CURRSYM="$"
elif [ "$CURRCODE" = "CNY" ]; then
	CURRSYM="¥"
elif [ "$CURRCODE" = "COP" ]; then
        CURRSYM="$"
elif [ "$CURRCODE" = "CRC" ]; then
        CURRSYM="₡"
elif [ "$CURRCODE" = "HRK" ]; then
        CURRSYM="kn"
elif [ "$CURRCODE" = "CUP" ]; then
        CURRSYM="₱"
elif [ "$CURRCODE" = "CZK" ]; then
        CURRSYM="Kč"
elif [ "$CURRCODE" = "DKK" ]; then
        CURRSYM="kr"
elif [ "$CURRCODE" = "DOP" ]; then
        CURRSYM="RD$"
elif [ "$CURRCODE" = "XCD" ]; then
        CURRSYM="$"
elif [ "$CURRCODE" = "EGP" ]; then
        CURRSYM="£"
elif [ "$CURRCODE" = "SVC" ]; then
        CURRSYM="$"
elif [ "$CURRCODE" = "EUR" ]; then
        CURRSYM="€"
elif [ "$CURRCODE" = "FKP" ]; then
        CURRSYM="£"
elif [ "$CURRCODE" = "FJD" ]; then
        CURRSYM="$"
elif [ "$CURRCODE" = "GHS" ]; then
        CURRSYM="¢"
elif [ "$CURRCODE" = "GIP" ]; then
        CURRSYM="£"
elif [ "$CURRCODE" = "GTQ" ]; then
        CURRSYM="Q"
elif [ "$CURRCODE" = "GGP" ]; then
        CURRSYM="£"
elif [ "$CURRCODE" = "GYD" ]; then
        CURRSYM="$"
elif [ "$CURRCODE" = "HNL" ]; then
        CURRSYM="L"
elif [ "$CURRCODE" = "HKD" ]; then
        CURRSYM="$"
elif [ "$CURRCODE" = "HUF" ]; then
        CURRSYM="Ft"
elif [ "$CURRCODE" = "ISK" ]; then
        CURRSYM="kr"
elif [ "$CURRCODE" = "INR" ]; then
        CURRSYM="&#8377;"
elif [ "$CURRCODE" = "IDR" ]; then
        CURRSYM="Rp"
elif [ "$CURRCODE" = "IRR" ]; then
        CURRSYM="﷼"
elif [ "$CURRCODE" = "IMP" ]; then
        CURRSYM="£"

elif [ "$CURRCODE" = "ILS" ]; then
        CURRSYM="₪"
elif [ "$CURRCODE" = "JMD" ]; then
        CURRSYM="J$"
elif [ "$CURRCODE" = "JPY" ]; then
        CURRSYM="¥"
elif [ "$CURRCODE" = "JEP" ]; then
        CURRSYM="£"
elif [ "$CURRCODE" = "KZT" ]; then
        CURRSYM="лв"
elif [ "$CURRCODE" = "KPW" ]; then
        CURRSYM="₩"
elif [ "$CURRCODE" = "KRW" ]; then
        CURRSYM="₩"
elif [ "$CURRCODE" = "KGS" ]; then
        CURRSYM="лв"
elif [ "$CURRCODE" = "LAK" ]; then
        CURRSYM="₭"
elif [ "$CURRCODE" = "LBP" ]; then
        CURRSYM="£"
elif [ "$CURRCODE" = "LRD" ]; then
        CURRSYM="$"
elif [ "$CURRCODE" = "MKD" ]; then
        CURRSYM="ден"
elif [ "$CURRCODE" = "MYR" ]; then
        CURRSYM="RM"
elif [ "$CURRCODE" = "MUR" ]; then
        CURRSYM="₨"
elif [ "$CURRCODE" = "MXN" ]; then
        CURRSYM="$"
elif [ "$CURRCODE" = "MNT" ]; then
        CURRSYM="₮"
elif [ "$CURRCODE" = "MZN" ]; then
        CURRSYM="MT"
elif [ "$CURRCODE" = "NAD" ]; then
        CURRSYM="$"
elif [ "$CURRCODE" = "NPR" ]; then
        CURRSYM="₨"
elif [ "$CURRCODE" = "ANG" ]; then
        CURRSYM="ƒ"
elif [ "$CURRCODE" = "NZD" ]; then
        CURRSYM="$"
elif [ "$CURRCODE" = "NIO" ]; then
        CURRSYM="C$"
elif [ "$CURRCODE" = "NGN" ]; then
        CURRSYM="₦"
elif [ "$CURRCODE" = "NOK" ]; then
        CURRSYM="kr"
elif [ "$CURRCODE" = "OMR" ]; then
        CURRSYM="﷼"

elif [ "$CURRCODE" = "PKR" ]; then
        CURRSYM="₨"
elif [ "$CURRCODE" = "PAB" ]; then
        CURRSYM="B/."
elif [ "$CURRCODE" = "PYG" ]; then
        CURRSYM="Gs"
elif [ "$CURRCODE" = "PEN" ]; then
        CURRSYM="S/."
elif [ "$CURRCODE" = "PHP" ]; then
        CURRSYM="₱"
elif [ "$CURRCODE" = "PLN" ]; then
        CURRSYM="zł"
elif [ "$CURRCODE" = "QAR" ]; then
        CURRSYM="﷼"
elif [ "$CURRCODE" = "RON" ]; then
        CURRSYM="lei"
elif [ "$CURRCODE" = "RUB" ]; then
        CURRSYM="&#8381;"
elif [ "$CURRCODE" = "SHP" ]; then
        CURRSYM="£"

elif [ "$CURRCODE" = "SAR" ]; then
        CURRSYM="﷼"
elif [ "$CURRCODE" = "RSD" ]; then
        CURRSYM="Дин."
elif [ "$CURRCODE" = "SCR" ]; then
        CURRSYM="₨"
elif [ "$CURRCODE" = "SGD" ]; then
        CURRSYM="$"
elif [ "$CURRCODE" = "SBD" ]; then
        CURRSYM="$"
elif [ "$CURRCODE" = "SOS" ]; then
        CURRSYM="S"
elif [ "$CURRCODE" = "ZAR" ]; then
        CURRSYM="R"
elif [ "$CURRCODE" = "LKR" ]; then
        CURRSYM="₨"
elif [ "$CURRCODE" = "SEK" ]; then
        CURRSYM="kr"

elif [ "$CURRCODE" = "CHF" ]; then
        CURRSYM="CHF"
elif [ "$CURRCODE" = "SRD" ]; then
        CURRSYM="$"
elif [ "$CURRCODE" = "SYP" ]; then
        CURRSYM="£"
elif [ "$CURRCODE" = "TWD" ]; then
        CURRSYM="NT$"
elif [ "$CURRCODE" = "THB" ]; then
        CURRSYM="฿"
elif [ "$CURRCODE" = "TTD" ]; then
        CURRSYM="TT$"
elif [ "$CURRCODE" = "TRY" ]; then
        CURRSYM="&#8378;"
elif [ "$CURRCODE" = "TVD" ]; then
        CURRSYM="$"
elif [ "$CURRCODE" = "UAH" ]; then
        CURRSYM="₴"
elif [ "$CURRCODE" = "GBP" ]; then
        CURRSYM="£"
elif [ "$CURRCODE" = "USD" ]; then
        CURRSYM="$"
elif [ "$CURRCODE" = "UYU" ]; then
        CURRSYM="$U"

elif [ "$CURRCODE" = "UZS" ]; then
        CURRSYM="лв"
elif [ "$CURRCODE" = "VEF" ]; then
        CURRSYM="Bs"
elif [ "$CURRCODE" = "VND" ]; then
        CURRSYM="₫"
elif [ "$CURRCODE" = "YER" ]; then
        CURRSYM="﷼"
elif [ "$CURRCODE" = "ZWD" ]; then
        CURRSYM="Z$"





fi

echo "$CURRSYM"

exit 0
